name: Keep Streamlit App Alive

on:
  # Manual trigger
  workflow_dispatch:

  # Daily scheduled trigger (adjust cron as needed)
  schedule:
    - cron: '0 0 * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # fetch all commits so we can pull

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure up-to-date with remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull --ff-only

      - name: Make an empty commit
        run: |
          git commit --allow-empty -m "chore: keep Streamlit app active"

      - name: Push empty commit
        run: |
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
