name: Keep Streamlit App Alive

# 1️⃣ Give the workflow write permission to repo contents
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (with full history & write creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # fetch all commits so we can fast-forward
          persist-credentials: true  # use GITHUB_TOKEN for pushes

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure up-to-date with remote
        run: |
          # Pull any new commits so our empty commit is a fast-forward
          git pull --ff-only

      - name: Make an empty commit
        run: |
          git commit --allow-empty -m "chore: keep Streamlit app active"

      - name: Push empty commit
        run: |
          git push origin HEAD:${{ github.ref_name }}
        # GITHUB_TOKEN is automatically used (persist-credentials: true)
